### ISSUE TITLE
| ERROR | 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by YotomiY** [MatteoFasulo/Whisper-TikTok#10]
**Describe the bug**
I ran the script : python main.py --model medium --tts en-US-EricNeural -> and all was going well until I had this error           
`` | ERROR | 'NoneType' object has no attribute 'lower'``
Full error (log)
```Traceback (most recent call last):
  File "C:\Users\User\Help\Whisper-TikTok\main.py", line 547, in <module>
    loop.run_until_complete(main())
  File "C:\Users\User\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\Help\Whisper-TikTok\main.py", line 209, in main
    highlight_words(srt_filename, subtitle_format=args.sub_format,
  File "C:\Users\User\Help\Whisper-TikTok\main.py", line 431, in highlight_words
    subtitle_format = subtitle_format.lower()
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Screenshots**
![image](https://github.com/MatteoFasulo/Whisper-TikTok/assets/115656415/4108a909-c5fc-445e-b7c5-07b5ab44de5e)
**Desktop:**
 - OS: Windows
 - No GPU

**Additional context**
I'm loving this project!!

**Comment by YotomiY** [comment]
I solve It

**Comment by MatteoFasulo** [comment]
> I solve It:
> ```
>     if subtitle_format is not None:
>         subtitle_format = subtitle_format.lower()
> ```

Hi, thx for also reporting the solution. Please open a pull request forking the code with these changes so I can merge the PR with main branch fixing definitely this issue.

- M
