### ISSUE TITLE
Error launching the new ui

### ISSUE THREAD

**Issue by YotomiY** [MatteoFasulo/Whisper-TikTok#18]
Traceback (most recent call last):
  File "C:\\Whisper-TikTok\utils.py", line 75, in get_info
    duration = float(audio_stream['duration'])
                     ~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\blocks.py", line 1177, in call_function
    prediction = await fn(*processed_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\utils.py", line 653, in async_wrapper
    response = await f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\\Whisper-TikTok\app.py", line 44, in generate_video
    video_creator.integrate_subtitles()
  File "C:\\Whisper-TikTok\src\video_creator.py", line 82, in integrate_subtitles
    final_video = prepare_background(
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\\Whisper-TikTok\src\video_prepare.py", line 12, in prepare_background
    video_duration = int(round(get_info(background_mp4).get('duration'), 0))
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\\Whisper-TikTok\utils.py", line 82, in get_info
    audio_stream['DURATION'], '%H:%M:%S.%f') - datetime.datetime.min).total_seconds()
    ~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by MatteoFasulo** [comment]
> Traceback (most recent call last): File "C:\Whisper-TikTok\utils.py", line 75, in get_info duration = float(audio_stream['duration']) ~~~~~~~~~~~~^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Python311\Lib\site-packages\gradio\queueing.py", line 489, in call_prediction output = await route_utils.call_process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api output = await app.get_blocks().process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\gradio\blocks.py", line 1561, in process_api result = await self.call_function( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\gradio\blocks.py", line 1177, in call_function prediction = await fn(*processed_input) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\gradio\utils.py", line 653, in async_wrapper response = await f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Whisper-TikTok\app.py", line 44, in generate_video video_creator.integrate_subtitles() File "C:\Whisper-TikTok\src\video_creator.py", line 82, in integrate_subtitles final_video = prepare_background( ^^^^^^^^^^^^^^^^^^^ File "C:\Whisper-TikTok\src\video_prepare.py", line 12, in prepare_background video_duration = int(round(get_info(background_mp4).get('duration'), 0)) ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Whisper-TikTok\utils.py", line 82, in get_info audio_stream['DURATION'], '%H:%M:%S.%f') - datetime.datetime.min).total_seconds() ~~~~~~~~~~~~^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable

Hi,
it seems an issue linked with #3, in that case there was a problem with `yt-dlp` while downloading the youtube video. I will check again for it

**Comment by YotomiY** [comment]
Solved!

**Comment by MatteoFasulo** [comment]
Alright, I've modified the download function to exclude the audio channel from the background video, at least for the time being, since there is currently no support for the background video's music.
