### ISSUE TITLE
Only 1 video on video.jsonn

### ISSUE THREAD

**Issue by YotomiY** [MatteoFasulo/Whisper-TikTok#23]
Hello,
When I put 2 or more stories in the video.json the script gives an error
Thanks

**Comment by MatteoFasulo** [comment]
Hey,

Thanks for letting me know about the issue with multiple stories in `video.json`. I've decided to drop that feature for now to keep things smooth.

I get it—using a `.json` file for video info isn't the coolest. I'm on the lookout for a better way to handle this. If you've got any ideas or preferences, feel free to share. Your input matters a lot.

**Comment by MatteoFasulo** [comment]
> Hello, When I put 2 or more stories in the video.json the script gives an error Thanks

Fixed the issue with multiple videos in the `video.json`. Now, in the UI, you can seamlessly select the background video and choose which video to generate directly from the `video.json` file. Please note that CLI support for choosing videos is in progress and will be available soon.

Give it a try, and let me know if you encounter any more issues. Appreciate your feedback!

Best.

**Comment by YotomiY** [comment]
Can we generate multiple stories at the same time?

**Comment by MatteoFasulo** [comment]
> Can we generate multiple stories at the same time?

While multiprocessing might not be feasible, I've successfully employed asyncio to enhance the processing speed. You can now choose any number of videos from the video.json file using the UI and generate their corresponding TikToks. The entire process is designed to be parallel, with the exception of the FFMPEG stage (where video encoding occurs sequentially, not in parallel). Nevertheless, the results are promising even without parallelism in that phase. Give it a try, and I look forward to hearing your feedback! 😊
