### ISSUE TITLE
New Google colab feature

### ISSUE THREAD

**Issue by YotomiY** [MatteoFasulo/Whisper-TikTok#24]
Hello,
I think it could be a very good feature for people that don't have a lot of resources in their computer.
In addition, it is now possible to do so thanks to the gradio interface. I will my self try to create the notebook.

Thanks

**Comment by MatteoFasulo** [comment]
> Hello, I think it could be a very good feature for people that don't have a lot of resources in their computer. In addition, it is now possible to do so thanks to the gradio interface. I will my self try to create the notebook.
> 
> Thanks

Hi @YotomiY,

Thanks for your input! Your idea of using the Gradio interface and creating a notebook for this feature sounds promising. Keep me updated on your progress. If you run into any issues or have questions, feel free to reach out.

Thanks again,
Matteo
