### ISSUE TITLE
KeyError 'DURATION' and Paths

### ISSUE THREAD

**Issue by remy-vallot** [MatteoFasulo/Whisper-TikTok#3]
Hello,

**Description of the bug**
The path system is not working for reaching folders. Folders and files are created but I ran into errors when it calls the path. I modified it with my absolute path each time. (for mp3/srt file creation, background folder and mp3/srt folder)
The second problem is the KeyError 'DURATION'

**Here is the log file output.**

> Traceback (most recent call last):
>   File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\code\main.py", line 423, in <module>
>     loop.run_until_complete(main())
>   File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\code\main.py", line 171, in main
>     file_info = get_info(background_mp4, verbose=args.verbose)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\code\main.py", line 221, in get_info
>     duration = (datetime.datetime.strptime(audio_stream['DURATION'], '%H:%M:%S.%f') - datetime.datetime.min).total_seconds()
>                                            ~~~~~~~~~~~~^^^^^^^^^^^^
> KeyError: 'DURATION'

I have tried replacing DURATION with duration like on previous lines but this does not fix it.

**My desktop**
Windows 11 ( I've tried also on WSL2)
Python 3.11.4

Thanks in advance for the fix.

_PS : Idea : it could be great to define all the folders. For example, the output folder could be created automatically._

**Comment by MatteoFasulo** [comment]
> Hello,
> 
> **Description of the bug** The path system is not working for reaching folders. Folders and files are created but I ran into errors when it calls the path. I modified it with my absolute path each time. (for mp3/srt file creation, background folder and mp3/srt folder) The second problem is the KeyError 'DURATION'
> 
> **Here is the log file output.**
> 
> > Traceback (most recent call last):
> > File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\code\main.py", line 423, in 
> > loop.run_until_complete(main())
> > File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
> > return future.result()
> > ^^^^^^^^^^^^^^^
> > File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\code\main.py", line 171, in main
> > file_info = get_info(background_mp4, verbose=args.verbose)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\code\main.py", line 221, in get_info
> > duration = (datetime.datetime.strptime(audio_stream['DURATION'], '%H:%M:%S.%f') - datetime.datetime.min).total_seconds()
> > ~~~~~~~~~~~~^^^^^^^^^^^^
> > KeyError: 'DURATION'
> 
> I have tried replacing DURATION with duration like on previous lines but this does not fix it.
> 
> **My desktop** Windows 11 ( I've tried also on WSL2) Python 3.11.4
> 
> Thanks in advance for the fix.
> 
> _PS : Idea : it could be great to define all the folders. For example, the output folder could be created automatically._

Hi,
try out the new release (v1.0.3) that should fix the issue with relative paths. 
The KeyError 'DURATION' is occurring when you are trying to access the 'DURATION' key in the `audio_stream` dictionary, but it seems that this key is not present in the dictionary. This likely indicates that the metadata you're trying to extract doesn't contain a 'DURATION' field. 

Regarding the second issue, the availability of metadata fields like 'DURATION' depends on the codec and the specific video or audio file you are working with. Not all media files will have the same set of metadata fields, and some fields may be missing. You should check the available metadata keys in the `audio_stream` dictionary before trying to access 'DURATION'. You can do this by printing the `audio_stream` dictionary and inspecting its contents. 
Paste here the output of the following line after the definition of audio_stream:

```python
print(audio_stream)
```

**Comment by MatteoFasulo** [comment]
> Hello, Thanks for the path fix, this seems to work.
> 
> For the 'DURATION' bug, I use the downloaded youtube video when executing the program with
> 
> ```
> python main.py
> ```
> 
> the audio stream contains theses informations
> 
> `{'index': 0, 'codec_name': 'opus', 'codec_long_name': 'Opus (Opus Interactive Audio Codec)', 'codec_type': 'audio', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'sample_fmt': 'fltp', 'sample_rate': '48000', 'channels': 2, 'channel_layout': 'stereo', 'bits_per_sample': 0, 'initial_padding': 312, 'r_frame_rate': '0/0', 'avg_frame_rate': '0/0', 'time_base': '1/1000', 'start_pts': -7, 'start_time': '-0.007000', 'extradata_size': 19, 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0, 'captions': 0, 'descriptions': 0, 'metadata': 0, 'dependent': 0, 'still_image': 0}, 'tags': {'language': 'eng'}}`
> 
> Thanks for your help and time!

it seems a problem related to **yt-dlp**. Are you using the default background video (https://www.youtube.com/watch?v=intRX7BRA90)?

in that case, paste also the output of **video_stream** or the url of the video that you are downloading.

**Comment by MatteoFasulo** [comment]
> Yes I am using the default background video.
> 
> The video stream output returns None.

what's the output of this?
![image](https://github.com/MatteoFasulo/Whisper-TikTok/assets/74818541/a099b2f4-bbfa-44c5-950b-57fcd7731bac)

**Comment by MatteoFasulo** [comment]
> Here is the probe variable
> 
> {'streams': [{'index': 0, 'codec_name': 'opus', 'codec_long_name': 'Opus (Opus Interactive Audio Codec)', 'codec_type': 'audio', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'sample_fmt': 'fltp', 'sample_rate': '48000', 'channels': 2, 'channel_layout': 'stereo', 'bits_per_sample': 0, 'initial_padding': 312, 'r_frame_rate': '0/0', 'avg_frame_rate': '0/0', 'time_base': '1/1000', 'start_pts': -7, 'start_time': '-0.007000', 'extradata_size': 19, 'disposition': {'default': 1, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0, 'captions': 0, 'descriptions': 0, 'metadata': 0, 'dependent': 0, 'still_image': 0}, 'tags': {'language': 'eng'}}], 'format': {'filename': '1_hour_22_minutes_of_relaxing_Minecraft_Parkour_60fps_Scenic_Download_in_the_Description-[intRX7BRA90].f251.webm', 'nb_streams': 1, 'nb_programs': 0, 'format_name': 'matroska,webm', 'format_long_name': 'Matroska / WebM', 'start_time': '-0.007000', 'duration': '4919.341000', 'size': '78352191', 'bit_rate': '127419', 'probe_score': 100, 'tags': {'encoder': 'google/video-file'}}}
> 
> But sometimes it doesn't reach the line where I print probe and outputs this error
> 
> [17:31:33] | ERROR | b'ffprobe version 6.0-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg main.py:266 developers\r\n built with gcc 12.2.0 (Rev10, Built by MSYS2 project)\r\n configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint\r\n libavutil 58. 2.100 / 58. 2.100\r\n libavcodec 60. 3.100 / 60. 3.100\r\n libavformat 60. 3.100 / 60. 3.100\r\n libavdevice 60. 1.100 / 60. 1.100\r\n libavfilter 9. 3.100 / 9. 3.100\r\n libswscale 7. 1.100 / 7. 1.100\r\n libswresample 4. 10.100 / 4. 10.100\r\n libpostproc 57. 1.100 / 57. 1.100\r\n Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!\r\n moov atom not found\r\n1_hour_22_minutes_of_relaxing_Minecraft_Parkour_60fps_Scenic_Download_in_the_Description -.temp.mp4: Invalid data found when processing input\r\n'

I changed the ffprobe command with a subprocess, can you tell me if it is working with the latest commit version?

**Comment by MatteoFasulo** [comment]
> It doesn't seem to work
> 
> I got a new error : Traceback (most recent call last): File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\main.py", line 453, in loop.run_until_complete(main()) File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\main.py", line 173, in main final_video = prepare_background( ^^^^^^^^^^^^^^^^^^^ File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\main.py", line 271, in prepare_background audio_info = get_info(filename_mp3) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\remyv\Documents\VS CODE CODES\Whisper-TikTok\main.py", line 237, in get_info duration = float(result.stdout) ^^^^^^^^^^^^^^^^^^^^ ValueError: could not convert string to float: b'output\Crazy_facts_that_you_did_not_know\Crazy_facts_that_you_did_not_know_4.mp3: No such file or directory\r\n'
> 
> My output folder is named output and is in the whipser-tiktok folder.

have you already tried to change the **path** value in **video.json**? The output folder is where all the edited tiktok videos are created with FFMPEG while the path is where the mp3 and srt file are created. The path folder should be different from the output folder.
![image](https://github.com/MatteoFasulo/Whisper-TikTok/assets/74818541/cc2684cd-d646-4d0e-b36b-f787ac7c7804)

**Comment by MatteoFasulo** [comment]
> detected only with low score of 1, misdetection possible!\r\n moov atom
> not

It appears that the issue is related to an error in the `ffprobe` call. To confirm whether `ffprobe` is functioning correctly, you can try two different approaches:

1. Utilize the `--url` argument when executing `main.py` and attempt to process a different video. You can find several examples in the Readme for reference.

2. Remove the "background" folder, which will prompt `yt-dlp` to download the background video again. Some users have suggested that the error may be due to a corrupted file in the existing background folder.

If neither of these approaches resolves the issue, it may be necessary to conduct further research to pinpoint the exact cause of the problem.

**Comment by MatteoFasulo** [comment]
> Using the --url seems to create a mp4 file but the file is said to be corrupted and can't be opened.
> Also I've tried removing the background folder more than once but nothing changed

Are you using the yt-dlp of requirements.txt?
