### ISSUE TITLE
can't open

### ISSUE THREAD

**Issue by GreenAA** [MatteoFasulo/Whisper-TikTok#39]
https://convert.streamlit.app/

**Comment by GreenAA** [comment]
and can't install telepathy 
win 11, vs 22, vs code 

![Screenshot 03-05-2024 12 44 07](https://github.com/MatteoFasulo/Whisper-TikTok/assets/87846163/41651be0-cbfa-46fe-95e3-dbd91e66eae5)


': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects
PS C:\PycharmP\Telepathy>

**Comment by MatteoFasulo** [comment]
> and can't install telepathy win 11, vs 22, vs code
> 
> ![Screenshot 03-05-2024 12 44 07](https://private-user-images.githubusercontent.com/87846163/310142485-41651be0-cbfa-46fe-95e3-dbd91e66eae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDg1NDYsIm5iZiI6MTcwOTY0ODI0NiwicGF0aCI6Ii84Nzg0NjE2My8zMTAxNDI0ODUtNDE2NTFiZTAtY2JmYS00NmZlLTk1ZTMtZGJkOTFlNjZlYWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE0MTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZTExNjUxNWIwNmM5OTNhZDIyZTFhYWFiNjIyOGRkOWY0N2U1OTU4ZjNiYzdiMzU3NTNjMTZkZjFjNTkwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzseSHZzr1KLRKGnpyUBL6wOyV2nOVvEUTdj3AwnuKI)
> 
> ': No such file or directory error: command 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe' failed with exit code 2 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pandas Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects PS C:\PycharmP\Telepathy>

This seems an issue with the combination of your python version, pandas library version you are trying to install and your operating system. I was aware of this kind of issues in Windows (due to missing of specific Microsoft Visual C++ version to compile the library). I can suggest you to try that in a linux environment (if possible) or under WSL if you still want to use windows.

Please give me more information about your python version and the specific version of pandas you are trying to install.

**Comment by GreenAA** [comment]
thanks bro 

i uinstall all py version 9,11,12.2 and install only py 11.7 verion 

so is install ok , but i get this error  , why ? thanks

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Scripts\telepathy.exe\__main__.py", line 7, in <module>
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telepathy\telepathy.py", line 226, in cli
    client = TelegramClient(phone_number, api_id, api_hash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\telegrambaseclient.py", line 275, in __init__
    session = SQLiteSession(session)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\sessions\sqlite.py", line 47, in __init__      
    c = self._cursor()
        ^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\sessions\sqlite.py", line 242, in _cursor      
    self._conn = sqlite3.connect(self.filename,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
ᐧ

**Comment by MatteoFasulo** [comment]
> thanks bro
> 
> i uinstall all py version 9,11,12.2 and install only py 11.7 verion
> 
> so is install ok , but i get this error , why ? thanks
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Scripts\telepathy.exe__main__.py", line 7, in File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 829, in **call** return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 782, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 610, in invoke return callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telepathy\telepathy.py", line 226, in cli client = TelegramClient(phone_number, api_id, api_hash) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\telegrambaseclient.py", line 275, in **init** session = SQLiteSession(session) ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\sessions\sqlite.py", line 47, in **init** c = self._cursor() ^^^^^^^^^^^^^^ File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\sessions\sqlite.py", line 242, in _cursor self._conn = sqlite3.connect(self.filename, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ sqlite3.OperationalError: unable to open database file ᐧ

Can't reproduce, can you give me more info about where are you trying to run the code (directory, folder)?

**Comment by GreenAA** [comment]
bro i renistall the telepathy add id, hash , phone .. and get thi erro again . why ? 

thanksTraceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Scripts\telepathy.exe\__main__.py", line 7, in <module>
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telepathy\telepathy.py", line 226, in cli
    client = TelegramClient(phone_number, api_id, api_hash)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\client\telegrambaseclient.py", line 275, in __init__
    session = SQLiteSession(session)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\sessions\sqlite.py", line 47, in __init__
    c = self._cursor()
        ^^^^^^^^^^^^^^
  File "C:\Users\eyal\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\sessions\sqlite.py", line 242, in _cursor
    self._conn = sqlite3.connect(self.filename,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

**Comment by GreenAA** [comment]
i tell you what i do .. 

install the app . put id >> hash >> phone num >> security code > then i get error . 

one thime i try open feom cmd >> path to telepathy folder >> and get error 
second time from the vs code > telepathy forlder terminal >> get also the error . 

i have py 3.11.7  with py 12.2 is not working

**Comment by MatteoFasulo** [comment]
As I said, it's either a permission error or you are trying to run the command from a path where there is no such file. The problem is from where you are running the program. 

Before diving into the issue, the maintainers will need to relax the pandas version requirements (out of date) otherwise new python version will not work with Telepathy correctly.

**Comment by GreenAA** [comment]
for me not working with python 3.9.1

**Comment by MatteoFasulo** [comment]
> for me not working with python 3.9.1

Did you install the pypi version (pip install ...) or the source version (cloning the repository) ?

**Comment by GreenAA** [comment]
https://github.com/MatteoFasulo/Whisper-TikTok/assets/87846163/44ad3d81-e9c9-427d-a564-48efdb3da86f

try install from pip3 / pip but get error . so from git 

with python 3.9.1 / 11.7 

first thie is work 
second time is error . 

you can see record
thanks bro

**Comment by GreenAA** [comment]
https://github.com/MatteoFasulo/Whisper-TikTok/assets/87846163/7f01b3c6-907b-4129-b038-17b4817fc002

now yes i install from pip3 is a same after i add id , hash , phone , i get info about durov and second time i get error

**Comment by GreenAA** [comment]
![Screenshot 03-16-2024 17 54 37](https://github.com/MatteoFasulo/Whisper-TikTok/assets/87846163/b224c45c-09b2-409d-b3cf-99beadd88296)


after i install from pip3 , is start but with error . 

meybe telehon version is the problem?

**Comment by GreenAA** [comment]
BRO I FORMAT MY PS RO WIN 11 ,,, AND TRY INSTALL AGAIN FROM PIP 3 ,, ALL
INSTALL FIRST TIME I TRY RUN IT I GET AGAIN ERROR , SAME ERROR

I THINK IS BUG



ᐧ
