### ISSUE TITLE
我是小白，基础太差，我想照葫芦画瓢学习下，能不能做给windows系统本地安装的视频教程？

### ISSUE THREAD

**Issue by fuxin-mail** [MatteoFasulo/Whisper-TikTok#41]
Execute the command according to the tutorial   git clone https://github.com/MatteoFasulo/Whisper-TikTok.git
'git' It is not an internal or external command, nor a runnable program or batch file
Warning: PowerShell Detected that you may be using a screen reader and it has been disabled for compatibility purposes PSReadLine。If you would like to re-enable it, please run "Import-Module PSReadLine"。

PS D:\Program Files\Whisper-TikTok-2.0.2\Whisper-TikTok-2.0.2> streamlit run app.py --server.port=8501 --server.address=0.0.0.0
streamlit : Unable to“streamlit”The item is identified as cmdlet、The name of the function, script file, or executable program is incorrect. Please check the spelling of the name, and if a path was included, ensure the path is correct, and try again.

Location: Line 1, Character 1
+ streamlit run app.py --server.port=8501 --server.address=0.0.0.0
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (streamlit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Program Files\Whisper-TikTok-2.0.2\Whisper-TikTok-2.0.2> git clone https://github.com/MatteoFasulo/Whisper-TikTok.git
git : Unable to“git”The item is identified as cmdlet、The name of the function, script file, or executable program is incorrect. Please check the spelling of the name, and if a path was included, ensure the path is correct, and try again.

Location: Line 1, Character 1
+ git clone https://github.com/MatteoFasulo/Whisper-TikTok.git
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Program Files\Whisper-TikTok-2.0.2\Whisper-TikTok-2.0.2>

Didn't succeed, but thanks anyway!Sorry! I don't speak English well, this is AI translation. I don't know if you can understand it?If it's convenient, I hope you could create an installation and usage tutorial for Windows.

**Comment by MatteoFasulo** [comment]
Hi @fuxin-mail,
Could you please rewrite this in English so I can understand it?
