### ISSUE TITLE
Highlight not working properly

### ISSUE THREAD

**Issue by remy-vallot** [MatteoFasulo/Whisper-TikTok#7]
Hello ! 
First, thank you for the new release, it works nice !

I've noted that the generated video underlines the spoken word and does not highlight it like on the demo video.
I've looked up the `whisper.get_writer` part in the lib and it seems to underline the word with the <u> tag in iterate_result.

Is it possible to modify the whisper lib in order to make it look like the demo code or am I missing something?

Thanks again for your time

**Comment by MatteoFasulo** [comment]
Hi,
I already submitted a [pull request to OpenAI/whisper](https://github.com/openai/whisper/pull/1704) asking to introduce a **subtitle_format** and word highlighting. Still waiting for an answer from the maintainer

**Comment by MatteoFasulo** [comment]
Clone the repository again and use the new CLI arguments for subtitle format and font color.

**Comment by MatteoFasulo** [comment]
@remy-vallot did you manage to try the new release with subtitle format and font color?
